name: 'Go-release'
description: 'Run goreleaser'
inputs:
  flags:
    description: Extra flags for goreleaser
    default: ''
  github-token:
    description: 'Token to login to GHCR and pull image - steps skipped if not provided'
    default: ''  
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: release --clean ${{ inputs.flags }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
