name: 👷 publish dev

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  goreleaser:
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flags: --snapshot

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            dist/**/*.zip
            dist/**/*.tar.gz
